# Generated by Django 5.2.1 on 2025-05-15 18:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FULL", "Fully Funded"),
                            ("PARTIAL", "Partial"),
                            ("TUITION", "Tuition Waiver"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "eligible_majors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("min_gpa", models.FloatField(blank=True, null=True)),
                ("language_requirements", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("source_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserScholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SAVED", "Saved"),
                            ("APPLIED", "Applied"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                        ],
                        default="SAVED",
                        max_length=10,
                    ),
                ),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
                ("documents", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("reminder_set", models.BooleanField(default=False)),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scholarships.scholarship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "scholarship")},
            },
        ),
    ]
